---
title: "Nrf2 BL6 PEITC 16S Microbiome Logit-Transformed Data Modeling"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
---


```{r Data, warning=FALSE,echo=FALSE,message=FALSE}
# html_notebook: default

require(data.table)
require(phyloseq)
require(ggplot2)
require(plotly)
require(DT)
require(lmerTest)
source("source/functions_v2.R")

# Load data----
# Counts
load("data/ps.RData")

# Taxonomy
load("data/taxa.plus.RData")
taxa <- data.table(seq16s = rownames(taxa.plus),
                   taxa.plus)

# Samples
# ps@sam_data
load("data/samples.RData")
samples$Sample <- substr(x = samples$Name,
                         start = 1,
                         stop = 5)
samples$Sample[samples$Sample %in% c("4A_S1",
                                     "4B_S2",
                                     "4C_S3")] <- 
  substr(x = samples$Sample[samples$Sample %in% c("4A_S1",
                                                  "4B_S2",
                                                  "4C_S3")],
         start = 1,
         stop = 2)
samples$MouseID <- substr(x = samples$Sample,
                         start = 2,
                         stop = 5)
# DT::datatable(samples)
```

## Relative Abundance in Samples at Different Taxonomic Ranks
```{r Tax, warning=FALSE,echo=FALSE,message=FALSE}
# keep controls and PEITCs at weeks 5 and 9 only
w59 <- prune_samples(samples = sample_names(ps)[!(sample_names(ps) %in%
                                                    c("4A",
                                                      "4B",
                                                      "4C",
                                                      "Undetermined"))],
                    x = ps)
# OTU table
otu <- t(w59@otu_table@.Data)
otu <- data.table(seq16s = rownames(otu),
                  otu)

# Merge taxonomy and counts tables----
dt1 <- merge(taxa,
             otu,
             by = "seq16s")
dt1$seq16s <- NULL

# Remove archea and eucaryota----
dt1 <- droplevels(dt1[Kingdom == "Bacteria", ])
# 10,197 out of 10,759 rows left

# Remove rows with all zeros----
ndx.keep <- rowSums(dt1[, `5A1-C`:`9C3-P`]) > 0
dt1 <- dt1[ndx.keep, ]
# 9,877 rows left
```

### 1. Class
```{r Class, warning=FALSE,echo=FALSE,message=FALSE,fig.width=10,fig.height=7}
tax <- "Class"
dt2 <- counts_ra_by_tax_rank(dt1, tax)

mu <- aggregate(dt2$RA,
                by = list(Tax = dt2$Tax,
                          Week = dt2$Week,
                          Diet = dt2$Diet),
                FUN = "mean")

lvls <- aggregate(dt2$RA,
                  by = list(Tax = dt2$Tax),
                  FUN = "mean")
lvls <- lvls$Tax[order(lvls$x,
                       decreasing = TRUE)]

dt2$Tax <- factor(dt2$Tax,
                  levels = lvls)

dt2 <- droplevels(dt2)
dt2[, lgt := log(1 + (RA/(1-RA)))]
# length(unique(dt2$Tax))
# 26 unique classes

dt2$Group <- paste("Week",
                   dt2$Week,
                   dt2$Diet)
# unique(dt2$grp)
dt2$Group <- factor(dt2$Group,
                    levels = c("Week 5 AIN93M Control",
                               "Week 9 AIN93M Control",
                               "Week 5 PEITC",
                               "Week 9 PEITC"))

# Boxplots for Classes with RA ~>1% (minus ----
over1pct <- levels(dt2$Tax)[1:7]

for (i in 1:length(over1pct)) {
  tmp <- droplevels(dt2[Tax == over1pct[i], ])
  
  p1 <- ggplot(data = tmp) +
    facet_wrap(~ Sex,
               nrow = 1) +
    geom_line(aes(x = Group,
                  y = RA,
                  group = MouseID),
              size = 1,
              position = position_dodge(0.3)) + 
    geom_point(aes(x = Group,
                   y = RA,
                   fill = MouseID),
               size = 3,
               alpha = 0.6,
               shape = 21,
               position = position_dodge(0.3)) + 
    scale_x_discrete("Diet/Week") + 
    scale_y_continuous("Relative Abundance") + 
    scale_fill_discrete("Mouse ID") +
    ggtitle(paste(tax,
                  over1pct[i],
                  sep = ": ")) +
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.x = element_text(angle = 45,
                                     hjust = 1))
  print(ggplotly(p1))
  
  p2 <- ggplot(data = tmp) +
    facet_wrap(~ Sex,
               nrow = 1) +
    geom_line(aes(x = Group,
                  y = lgt,
                  group = MouseID),
              size = 1,
              position = position_dodge(0.3)) + 
    geom_point(aes(x = Group,
                   y = lgt,
                   fill = MouseID),
               size = 3,
               alpha = 0.6,
               shape = 21,
               position = position_dodge(0.3)) + 
    scale_x_discrete("Diet/Week") + 
    scale_y_continuous("Logit of Relative Abundance") + 
    scale_fill_discrete("Mouse ID") +
    ggtitle(paste(tax,
                  over1pct[i],
                  sep = ": ")) +
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.x = element_text(angle = 45,
                                     hjust = 1))
  print(ggplotly(p2))
  
  m1 <- lmerTest::lmer(lgt ~ Diet + Week + Sex + (1|MouseID),
                       # weights = 1/(Counts + 0.5),
                       data = tmp)
  print(summary(m1))
}
```

### 2. Order
```{r Order, warning=FALSE,echo=FALSE,message=FALSE,fig.width=10,fig.height=7}
tax <- "Order"
dt2 <- counts_ra_by_tax_rank(dt1, tax)

mu <- aggregate(dt2$RA,
                by = list(Tax = dt2$Tax,
                          Week = dt2$Week,
                          Diet = dt2$Diet),
                FUN = "mean")

lvls <- aggregate(dt2$RA,
                  by = list(Tax = dt2$Tax),
                  FUN = "mean")
lvls <- lvls$Tax[order(lvls$x,
                       decreasing = TRUE)]

dt2$Tax <- factor(dt2$Tax,
                  levels = lvls)

dt2 <- droplevels(dt2)
dt2[, lgt := log(1 + (RA/(1-RA)))]
# length(unique(dt2$Tax))
# 26 unique classes

dt2$Group <- paste("Week",
                   dt2$Week,
                   dt2$Diet)
# unique(dt2$grp)
dt2$Group <- factor(dt2$Group,
                    levels = c("Week 5 AIN93M Control",
                               "Week 9 AIN93M Control",
                               "Week 5 PEITC",
                               "Week 9 PEITC"))

# Boxplots for Classes with RA ~>1% (minus ----
over1pct <- levels(dt2$Tax)[1:10]

for (i in 1:length(over1pct)) {
  tmp <- droplevels(dt2[Tax == over1pct[i], ])
  
  p1 <- ggplot(data = tmp) +
    facet_wrap(~ Sex,
               nrow = 1) +
    geom_line(aes(x = Group,
                  y = RA,
                  group = MouseID),
              size = 1,
              position = position_dodge(0.3)) + 
    geom_point(aes(x = Group,
                   y = RA,
                   fill = MouseID),
               size = 3,
               alpha = 0.6,
               shape = 21,
               position = position_dodge(0.3)) + 
    scale_x_discrete("Diet/Week") + 
    scale_y_continuous("Relative Abundance") + 
    scale_fill_discrete("Mouse ID") +
    ggtitle(paste(tax,
                  over1pct[i],
                  sep = ": ")) +
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.x = element_text(angle = 45,
                                     hjust = 1))
  print(ggplotly(p1))
  
  p2 <- ggplot(data = tmp) +
    facet_wrap(~ Sex,
               nrow = 1) +
    geom_line(aes(x = Group,
                  y = lgt,
                  group = MouseID),
              size = 1,
              position = position_dodge(0.3)) + 
    geom_point(aes(x = Group,
                   y = lgt,
                   fill = MouseID),
               size = 3,
               alpha = 0.6,
               shape = 21,
               position = position_dodge(0.3)) + 
    scale_x_discrete("Diet/Week") + 
    scale_y_continuous("Logit of Relative Abundance") + 
    scale_fill_discrete("Mouse ID") +
    ggtitle(paste(tax,
                  over1pct[i],
                  sep = ": ")) +
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.x = element_text(angle = 45,
                                     hjust = 1))
  print(ggplotly(p2))
  
  m1 <- lmerTest::lmer(lgt ~ Diet + Week + Sex + (1|MouseID),
                       # weights = 1/(Counts + 0.5),
                       data = tmp)
  print(summary(m1))
}
```

### 3. Family
```{r Family, warning=FALSE,echo=FALSE,message=FALSE,fig.width=10,fig.height=7}
tax <- "Family"
dt2 <- counts_ra_by_tax_rank(dt1, tax)

mu <- aggregate(dt2$RA,
                by = list(Tax = dt2$Tax,
                          Week = dt2$Week,
                          Diet = dt2$Diet),
                FUN = "mean")

lvls <- aggregate(dt2$RA,
                  by = list(Tax = dt2$Tax),
                  FUN = "mean")
lvls <- lvls$Tax[order(lvls$x,
                       decreasing = TRUE)]

dt2$Tax <- factor(dt2$Tax,
                  levels = lvls)

dt2 <- droplevels(dt2)
dt2[, lgt := log(1 + (RA/(1-RA)))]
# length(unique(dt2$Tax))
# 26 unique classes

dt2$Group <- paste("Week",
                   dt2$Week,
                   dt2$Diet)
# unique(dt2$grp)
dt2$Group <- factor(dt2$Group,
                    levels = c("Week 5 AIN93M Control",
                               "Week 9 AIN93M Control",
                               "Week 5 PEITC",
                               "Week 9 PEITC"))

# Boxplots for Classes with RA ~>1% (minus ----
over1pct <- levels(dt2$Tax)[1:17]

for (i in 1:length(over1pct)) {
  tmp <- droplevels(dt2[Tax == over1pct[i], ])
  
  p1 <- ggplot(data = tmp) +
    facet_wrap(~ Sex,
               nrow = 1) +
    geom_line(aes(x = Group,
                  y = RA,
                  group = MouseID),
              size = 1,
              position = position_dodge(0.3)) + 
    geom_point(aes(x = Group,
                   y = RA,
                   fill = MouseID),
               size = 3,
               alpha = 0.6,
               shape = 21,
               position = position_dodge(0.3)) + 
    scale_x_discrete("Diet/Week") + 
    scale_y_continuous("Relative Abundance") + 
    scale_fill_discrete("Mouse ID") +
    ggtitle(paste(tax,
                  over1pct[i],
                  sep = ": ")) +
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.x = element_text(angle = 45,
                                     hjust = 1))
  print(ggplotly(p1))
  
  p2 <- ggplot(data = tmp) +
    facet_wrap(~ Sex,
               nrow = 1) +
    geom_line(aes(x = Group,
                  y = lgt,
                  group = MouseID),
              size = 1,
              position = position_dodge(0.3)) + 
    geom_point(aes(x = Group,
                   y = lgt,
                   fill = MouseID),
               size = 3,
               alpha = 0.6,
               shape = 21,
               position = position_dodge(0.3)) + 
    scale_x_discrete("Diet/Week") + 
    scale_y_continuous("Logit of Relative Abundance") + 
    scale_fill_discrete("Mouse ID") +
    ggtitle(paste(tax,
                  over1pct[i],
                  sep = ": ")) +
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.x = element_text(angle = 45,
                                     hjust = 1))
  print(ggplotly(p2))
  
  m1 <- lmerTest::lmer(lgt ~ Diet + Week + Sex + (1|MouseID),
                       # weights = 1/(Counts + 0.5),
                       data = tmp)
  print(summary(m1))
}
```

### 4. Genus
```{r Genus, warning=FALSE,echo=FALSE,message=FALSE,fig.width=10,fig.height=7}
tax <- "Genus"
dt2 <- counts_ra_by_tax_rank(dt1, tax)

mu <- aggregate(dt2$RA,
                by = list(Tax = dt2$Tax,
                          Week = dt2$Week,
                          Diet = dt2$Diet),
                FUN = "mean")

lvls <- aggregate(dt2$RA,
                  by = list(Tax = dt2$Tax),
                  FUN = "mean")
lvls <- lvls$Tax[order(lvls$x,
                       decreasing = TRUE)]

dt2$Tax <- factor(dt2$Tax,
                  levels = lvls)

dt2 <- droplevels(dt2)
dt2[, lgt := log(1 + (RA/(1-RA)))]
# length(unique(dt2$Tax))
# 26 unique classes

dt2$Group <- paste("Week",
                   dt2$Week,
                   dt2$Diet)
# unique(dt2$grp)
dt2$Group <- factor(dt2$Group,
                    levels = c("Week 5 AIN93M Control",
                               "Week 9 AIN93M Control",
                               "Week 5 PEITC",
                               "Week 9 PEITC"))

# Boxplots for Classes with RA ~>1% (minus ----
over1pct <- levels(dt2$Tax)[1:20]

for (i in 1:length(over1pct)) {
  tmp <- droplevels(dt2[Tax == over1pct[i], ])
  
  p1 <- ggplot(data = tmp) +
    facet_wrap(~ Sex,
               nrow = 1) +
    geom_line(aes(x = Group,
                  y = RA,
                  group = MouseID),
              size = 1,
              position = position_dodge(0.3)) + 
    geom_point(aes(x = Group,
                   y = RA,
                   fill = MouseID),
               size = 3,
               alpha = 0.6,
               shape = 21,
               position = position_dodge(0.3)) + 
    scale_x_discrete("Diet/Week") + 
    scale_y_continuous("Relative Abundance") + 
    scale_fill_discrete("Mouse ID") +
    ggtitle(paste(tax,
                  over1pct[i],
                  sep = ": ")) +
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.x = element_text(angle = 45,
                                     hjust = 1))
  print(ggplotly(p1))
  
  p2 <- ggplot(data = tmp) +
    facet_wrap(~ Sex,
               nrow = 1) +
    geom_line(aes(x = Group,
                  y = lgt,
                  group = MouseID),
              size = 1,
              position = position_dodge(0.3)) + 
    geom_point(aes(x = Group,
                   y = lgt,
                   fill = MouseID),
               size = 3,
               alpha = 0.6,
               shape = 21,
               position = position_dodge(0.3)) + 
    scale_x_discrete("Diet/Week") + 
    scale_y_continuous("Logit of Relative Abundance") + 
    scale_fill_discrete("Mouse ID") +
    ggtitle(paste(tax,
                  over1pct[i],
                  sep = ": ")) +
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.x = element_text(angle = 45,
                                     hjust = 1))
  print(ggplotly(p2))
  
  m1 <- lmerTest::lmer(lgt ~ Diet + Week + Sex + (1|MouseID),
                       # weights = 1/(Counts + 0.5),
                       data = tmp)
  print(summary(m1))
}
```